name: testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: get build environment
      run: ./getBuildEnvironment.sh
    - name: get libraries
      run: ./getLibraries.sh
    - name: make
      run: |
        cd src
        make
