name: testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: getBuildEnvironment.sh
      run: ./getBuildEnvironment
    - name: getLibraries
      run: ./getLibraries.sh
    - name: make
      run: make
